### PR TITLE
Create codeql.yml

### PR DESCRIPTION
**Pull request by titungdup**

### CODE REVIEW

**Comment by sonam-serchan** [comment]
@boltdynamics Hey Pras, can you please take a look at the change and see if it's fine or complex. If all good, then let's merge it!

**Review by boltdynamics — COMMENTED** [review]
Hey @titungdup @sonam-serchan I did some research on CodeQL and we need github enterprise to be able to use some it the features.

Are we happy to use SonarCloud for now? I will go ahead and set it up. Lets see how we go with SonarCloud for now and we can make a switch later

**Comment by boltdynamics** [comment]
Done, SonarCloud has been enabled for this repository 👍 
image

**Comment by sonam-serchan** [comment]
Awesome @boltdynamics! I guess we don't need this PR then. Can we close it?

**Comment by boltdynamics** [comment]
> Awesome @boltdynamics! I guess we don't need this PR then. Can we close it?

Yes, I will let @titungdup do the honor 😉

**Comment by titungdup** [comment]
SonarCloud looks great @boltdynamics. Closing this PR.

**Pull request closed without merging**
